package assignment2;

public class Test11 {
	public static void main(String[] args)
	{
	try {
	 for (int i = 1; i <= 5; i++) 
	 {
	 System.out.print(i + " ");
	 }
	}
	catch (Exception e) {
	 System.out.println(e.getMessage());
	 }
	 System.out.println("\nOut of try-catch block");
	 }//1 2 3 4 5 and print Out of try-catch block inside there is no exception code
	 //there is no use of try-catch block
	}


